### ISSUE TITLE
PeSTo/md_analysis/data_manager /data_manager.py, "meta" does not exist

### ISSUE THREAD

**Issue by rubenalv** [LBM-EPFL/PeSTo#6]
I have tried to run PeSTo/md_analysis/apply_model_md.ipynb.
The folder "model" does not exist here, but I copied it from the root directory.
The from X import statements need to refer to "model."

In
`from CLoNe.clone import CLoNe`
"CLoNe" does not exist

The data "meta" does not exist, so the data_manager.py just throws a
`FileNotFoundError: [Errno 2] No such file or directory: 'database/meta'`

Also, the symlink for directory
`datasets/`
points to an non-existent location

Could you upload the data, for testing?

**Comment by chiarinival** [comment]
Hi Ruben!!!

We have faced the very same problem while attempting to run the "apply_model_md.ipynb" notebook. We encountered a keynote complaint in cell 7, probably linked to the missing "meta" file. As you, we created an ex-novo database folder under md_analysis and transferred there our .xtc and .pdb files. 

I wonder, did you manage to solve the error since you last reported? Any feedback would be greatly apprecciated. 

I share with you the last part of our error:

243 except KeyError as err: 
--> 244 raise UndefinedVariableError(key, is_local) from err
UndefinedVariableError: name 'pdbid' is not defined

Thanks a lot, 

Valerio

**Comment by rubenalv** [comment]
@chiarinival, I could not solve the actual error due to the missing directories, but I proposed a working solution here https://github.com/LBM-EPFL/PeSTo/issues/5
Unless you specifically want to run the apply_model_md.ipynb file, I would hope you can recreate that solution.
Cheers,
R
